
__all__ = ['ASC_IDENTIFIER', 'CANCEL_IDENTIFIER', 'CLEAR_IDENTIFIER', 'CLOSE_IDENTIFIER', 'DEFAULT_IDENTIFIER',
           'DESC_IDENTIFIER', 'SELECT_ALL_IDENTIFIER', 'SUBMIT_IDENTIFIER']

# GLOBAL VARIABLES
DEFAULT_IDENTIFIER = 'data-qa-id'

ASC_IDENTIFIER = 'asc'
CANCEL_IDENTIFIER = 'cancel'
CLEAR_IDENTIFIER = 'clear'
CLOSE_IDENTIFIER = 'close'
DESC_IDENTIFIER = 'desc'
SELECT_ALL_IDENTIFIER = 'select-all'
SUBMIT_IDENTIFIER = 'submit'
